#*****************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# EcEvrProto_project.tcl: Tcl script for re-creating project 'EcEvrProto_project'
#
# Generated by Vivado on Sat Sep 03 15:33:01 CEST 2022
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (EcEvrProto_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/vivado/slac/foobar/firmware/build/EcEvrProto/EcEvrProto_project.srcs/sources_1/imports/hdl/IlaWrappersPkg.vhd"
#    "/home/vivado/slac/foobar/firmware/build/EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/TimingGtp/TimingGtp.xci"
#    "/home/vivado/slac/foobar/firmware/build/EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/Ila_256/Ila_256.xci"
#    "/home/vivado/slac/foobar/firmware/build/EcEvrProto/EcEvrProto_project.srcs/utils_1/imports/synth_1/EcEvrProto.dcp"
#    "/home/vivado/slac/foobar/firmware/build/EcEvrProto/EcEvrProto_project.srcs/utils_1/imports/impl_1/EcEvrProto_routed.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCBasicTypesPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/IPAddrConfigPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/DeviceDna7.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/AddressGenerator.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254Pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Udp2BusPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/Bus2DRP.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/Bus2I2cStreamIF.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/Bus2SpiFlashIF.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/EEPROMContentPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/EEEmulPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254ESCPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EvrTxPDOPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_array_pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_math_pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/evr320_pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/Evr320ConfigPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EEPROMConfigPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EEPROMConfigurator.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCMbxPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/StrmFrameBuf.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCEoERx.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCEoETx.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCFoEPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCFoE.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCRxMbxMux.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCSmRx.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCTxMbxBuf.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCTxMbxErr.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCTxMbxMux.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/ESCTxPDO.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EcEvrBspPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/SynchronizerBit.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EcEvrBoardMap.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProtoPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/FoE2SpiPkg.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/gtp/TimingGtpPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/MicroUDPPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254Hbi.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Udp2BusMux.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254UdpBusPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254ESC.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/MicroUDPRx.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/IPV4ChkSum.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/MicroUDPTx.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/MicroUDPIPMux.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Udp2Bus.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/StrmFifoSync.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254ESCWrapper.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/evr320_dpram.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/evr320_buffer.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_logic_pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_sdp_ram.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_pulse_cc.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_async_fifo.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/evr320_timestamp.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/evr320_decoder.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_simple_cc.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_status_cc.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/evr320_udp2bus.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_clk_meas.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/pulse_shaper_dly_cfg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/evr320_udp2bus_wrapper.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EvrTxPDO.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/I2cProgrammer.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/StrmMux.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_bit_cc.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_i2c_master.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/PsiI2cStreamIF.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/I2cWrapper.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/SpiBitShifter.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/FoE2Spi.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/SpiMonitor.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/EcEvrWrapper.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/gtp/TimingGtp_cpll_railing.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/gtp/TimingGtp_common.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/gtp/TimingGtpWrapper.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/IcapE2Reg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/PwmCore.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProtoTop.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/lan9254-rtl-esc/hdl/Lan9254HbiImpl.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/ecevr-core/hdl/ZynqBspPkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/psi_common/hdl/psi_common_axi_pkg.vhd"
#    "/home/vivado/slac/foobar/firmwasubmodules/evr320/hdl/v6vlx_gtxe1_pkg.vhd"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto-clocks.xdc"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto-misc.xdc"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto-io.xdc"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto-io_timing.xdc"
#    "/home/vivado/slac/foobar/firmware/targets/EcEvrProto/hdl/EcEvrProto-clock_groups.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
#TS  set files [list \
#TS "[file normalize "$origin_dir/../EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/TimingGtp/TimingGtp.xci"]"\
#TS "[file normalize "$origin_dir/../EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/Ila_256/Ila_256.xci"]"\
#TS "[file normalize "$origin_dir/EcEvrProto_project.srcs/utils_1/imports/synth_1/EcEvrProto.dcp"]"\
#TS "[file normalize "$origin_dir/EcEvrProto_project.srcs/utils_1/imports/impl_1/EcEvrProto_routed.dcp"]"\
#TS  ]
#TS  foreach ifile $files {
#TS    if { ![file isfile $ifile] } {
#TS      puts " Could not find local file $ifile "
#TS      set status false
#TS    }
#TS  }

  set files [list \
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCBasicTypesPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/IPAddrConfigPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/DeviceDna7.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/AddressGenerator.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254Pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2BusPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/Bus2DRP.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/Bus2I2cStreamIF.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/Bus2SpiFlashIF.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/EEPROMContentPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/EEEmulPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EvrTxPDOPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_array_pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_math_pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/evr320_pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/Evr320ConfigPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EEPROMConfigPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EEPROMConfigurator.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCMbxPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmFrameBuf.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCEoERx.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCEoETx.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCFoEPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCFoE.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCRxMbxMux.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCSmRx.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxBuf.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxErr.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxMux.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxPDO.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EcEvrBspPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/SynchronizerBit.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EcEvrBoardMap.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProtoPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/FoE2SpiPkg.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/gtp/TimingGtpPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254Hbi.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2BusMux.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254UdpBusPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESC.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPRx.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/IPV4ChkSum.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPTx.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPIPMux.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2Bus.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmFifoSync.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCWrapper.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/evr320_dpram.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/evr320_buffer.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_logic_pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_sdp_ram.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_pulse_cc.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_async_fifo.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/evr320_timestamp.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/evr320_decoder.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_simple_cc.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_status_cc.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/evr320_udp2bus.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_clk_meas.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/pulse_shaper_dly_cfg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/evr320_udp2bus_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EvrTxPDO.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/I2cProgrammer.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmMux.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_bit_cc.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_i2c_master.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/PsiI2cStreamIF.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/I2cWrapper.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/SpiBitShifter.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/FoE2Spi.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/SpiMonitor.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/EcEvrWrapper.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/gtp/TimingGtp_cpll_railing.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/gtp/TimingGtp_common.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/gtp/TimingGtpWrapper.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/IcapE2Reg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/PwmCore.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProtoTop.vhd"]"\
 "[file normalize "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254HbiImpl.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto.vhd"]"\
 "[file normalize "$origin_dir/../submodules/ecevr-core/hdl/ZynqBspPkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/psi_common/hdl/psi_common_axi_pkg.vhd"]"\
 "[file normalize "$origin_dir/../submodules/evr320/hdl/v6vlx_gtxe1_pkg.vhd"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto-clocks.xdc"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto-misc.xdc"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto-io.xdc"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto-io_timing.xdc"]"\
 "[file normalize "$origin_dir/..//hdl/EcEvrProto-clock_groups.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/ip_repo"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]
set proj_part  "xc7a35tcsg325-2"

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "EcEvrProto_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "EcEvrProto_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part ${proj_part}

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "${proj_part}" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "1" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "1" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "1" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "1" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
#TS set obj [get_filesets sources_1]
#TS if { $obj != {} } {
#TS    set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo"]" $obj
#TS 
#TS    # Rebuild user ip_repo's index before adding any source files
#TS    update_ip_catalog -rebuild
#TS }

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCBasicTypesPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/IPAddrConfigPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/DeviceDna7.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/AddressGenerator.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254Pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Udp2BusPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/Bus2DRP.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/Bus2I2cStreamIF.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/Bus2SpiFlashIF.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/EEPROMContentPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/EEEmulPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/IlaWrappersPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EvrTxPDOPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_array_pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_math_pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/evr320_pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/Evr320ConfigPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EEPROMConfigPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EEPROMConfigurator.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCMbxPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/StrmFrameBuf.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCEoERx.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCEoETx.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCFoEPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCFoE.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCRxMbxMux.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCSmRx.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxBuf.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxErr.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxMux.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/ESCTxPDO.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EcEvrBspPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/SynchronizerBit.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EcEvrBoardMap.vhd"] \
 [file normalize "${origin_dir}/..//hdl/EcEvrProtoPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/FoE2SpiPkg.vhd"] \
 [file normalize "${origin_dir}/..//hdl/gtp/TimingGtpPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/MicroUDPPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254Hbi.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Udp2BusMux.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254UdpBusPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254ESC.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/MicroUDPRx.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/IPV4ChkSum.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/MicroUDPTx.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/MicroUDPIPMux.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Udp2Bus.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/StrmFifoSync.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCWrapper.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/evr320_dpram.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/evr320_buffer.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_logic_pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_sdp_ram.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_pulse_cc.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_async_fifo.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/evr320_timestamp.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/evr320_decoder.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_simple_cc.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_status_cc.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/evr320_udp2bus.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_clk_meas.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/pulse_shaper_dly_cfg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/evr320_udp2bus_wrapper.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EvrTxPDO.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/I2cProgrammer.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/StrmMux.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_bit_cc.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_i2c_master.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/PsiI2cStreamIF.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/I2cWrapper.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/SpiBitShifter.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/FoE2Spi.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/SpiMonitor.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/EcEvrWrapper.vhd"] \
 [file normalize "${origin_dir}/..//hdl/gtp/TimingGtp_cpll_railing.vhd"] \
 [file normalize "${origin_dir}/..//hdl/gtp/TimingGtp_common.vhd"] \
 [file normalize "${origin_dir}/..//hdl/gtp/TimingGtpWrapper.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/IcapE2Reg.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/PwmCore.vhd"] \
 [file normalize "${origin_dir}/..//hdl/EcEvrProtoTop.vhd"] \
 [file normalize "${origin_dir}/../submodules/lan9254-rtl-esc/hdl/Lan9254HbiImpl.vhd"] \
 [file normalize "${origin_dir}/..//hdl/EcEvrProto.vhd"] \
 [file normalize "${origin_dir}/../submodules/ecevr-core/hdl/ZynqBspPkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/psi_common/hdl/psi_common_axi_pkg.vhd"] \
 [file normalize "${origin_dir}/../submodules/evr320/hdl/v6vlx_gtxe1_pkg.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/IlaWrappersPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCBasicTypesPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/IPAddrConfigPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/DeviceDna7.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/AddressGenerator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254Pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2BusPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/Bus2DRP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/Bus2I2cStreamIF.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/Bus2SpiFlashIF.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/EEPROMContentPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/EEEmulPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EvrTxPDOPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_array_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_math_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/evr320_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/Evr320ConfigPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EEPROMConfigPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EEPROMConfigurator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCMbxPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmFrameBuf.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCEoERx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCEoETx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCFoEPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCFoE.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCRxMbxMux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCSmRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxBuf.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxErr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxMbxMux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/ESCTxPDO.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EcEvrBspPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/SynchronizerBit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EcEvrBoardMap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/EcEvrProtoPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/FoE2SpiPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/gtp/TimingGtpPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254Hbi.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2BusMux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254UdpBusPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESC.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/IPV4ChkSum.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/MicroUDPIPMux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Udp2Bus.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmFifoSync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254ESCWrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/evr320_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/evr320_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_logic_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_sdp_ram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_pulse_cc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_async_fifo.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/evr320_timestamp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/evr320_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_simple_cc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_status_cc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/evr320_udp2bus.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_clk_meas.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/pulse_shaper_dly_cfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/evr320_udp2bus_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EvrTxPDO.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/I2cProgrammer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/StrmMux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_bit_cc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_i2c_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/PsiI2cStreamIF.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/I2cWrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/SpiBitShifter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/FoE2Spi.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/SpiMonitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/EcEvrWrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/gtp/TimingGtp_cpll_railing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/gtp/TimingGtp_common.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/gtp/TimingGtpWrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/IcapE2Reg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/PwmCore.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/EcEvrProtoTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/lan9254-rtl-esc/hdl/Lan9254HbiImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/..//hdl/EcEvrProto.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/ecevr-core/hdl/ZynqBspPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/psi_common/hdl/psi_common_axi_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

set file "$origin_dir/../submodules/evr320/hdl/v6vlx_gtxe1_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "EcEvrProto" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Generate IPs
source "$origin_dir/genIla256.tcl"
source "$origin_dir/genTimingGtp.tcl"

#TS # Set 'sources_1' fileset object
#TS set obj [get_filesets sources_1]
#TS # Import local files from the original project
#TS set files [list \
#TS  [file normalize "${origin_dir}/../EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/TimingGtp/TimingGtp.xci" ]\
#TS ]
#TS set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

#TS # Set 'sources_1' fileset file properties for local files
#TS set file "TimingGtp/TimingGtp.xci"
#TS set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#TS set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
#TS set_property -name "registered_with_manager" -value "1" -objects $file_obj
#TS if { ![get_property "is_locked" $file_obj] } {
#TS   set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
#TS }


#TS # Set 'sources_1' fileset object
#TS set obj [get_filesets sources_1]
#TS # Import local files from the original project
#TS set files [list \
#TS  [file normalize "${origin_dir}/../EcEvrProto/EcEvrProto_project.srcs/sources_1/ip/Ila_256/Ila_256.xci" ]\
#TS ]
#TS set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#TS set file "Ila_256/Ila_256.xci"
#TS set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#TS set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
#TS set_property -name "registered_with_manager" -value "1" -objects $file_obj
#TS if { ![get_property "is_locked" $file_obj] } {
#TS   set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
#TS }

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/..//hdl/EcEvrProto-clocks.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/..//hdl/EcEvrProto-clocks.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/..//hdl/EcEvrProto-misc.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/..//hdl/EcEvrProto-misc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/..//hdl/EcEvrProto-io.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/..//hdl/EcEvrProto-io.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/..//hdl/EcEvrProto-io_timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/..//hdl/EcEvrProto-io_timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj
set_property -name "used_in" -value "implementation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/..//hdl/EcEvrProto-clock_groups.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/..//hdl/EcEvrProto-clock_groups.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "path_mode" -value "AbsoluteFirst" -objects $file_obj
set_property -name "used_in" -value "implementation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/..//hdl/EcEvrProto-misc.xdc"]" -objects $obj
set_property -name "target_part" -value "${proj_part}" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/..//hdl/EcEvrProto-misc.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "EcEvrProto" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "-d SIM_SPEED_UP" -objects $obj
set_property -name "xsim.simulate.runtime" -value "" -objects $obj

#TS # Set 'utils_1' fileset object
#TS set obj [get_filesets utils_1]
#TS # Import local files from the original project
#TS set files [list \
#TS  [file normalize "${origin_dir}/EcEvrProto_project.srcs/utils_1/imports/synth_1/EcEvrProto.dcp" ]\
#TS  [file normalize "${origin_dir}/EcEvrProto_project.srcs/utils_1/imports/impl_1/EcEvrProto_routed.dcp" ]\
#TS ]
#TS set imported_files [import_files -fileset utils_1 $files]

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
#TS set file "synth_1/EcEvrProto.dcp"
#TS set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
#TS set_property -name "netlist_only" -value "0" -objects $file_obj

#TS set file "impl_1/EcEvrProto_routed.dcp"
#TS set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
#TS set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part ${proj_part} -flow {Vivado Synthesis 2021} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2021" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "${proj_part}" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "write_incremental_synth_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
#TS set_property -name "steps.synth_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/synth.tcl"]" -objects $obj
set_property -name "steps.synth_design.tcl.pre" -value "[file normalize "$origin_dir/..//vivado/pre_synth_run.tcl"]" -objects $obj
#TS set_property -name "steps.synth_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/synth.tcl"]" -objects $obj
set_property -name "steps.synth_design.args.flatten_hierarchy" -value "none" -objects $obj
set_property -name "steps.synth_design.args.assert" -value "1" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part ${proj_part} -flow {Vivado Implementation 2021} -strategy "Performance_ExplorePostRoutePhysOpt" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]
  set_property flow "Vivado Implementation 2021" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "${proj_part}" -objects $obj
#TS set_property -name "incremental_checkpoint" -value "$proj_dir/EcEvrProto_project.srcs/utils_1/imports/impl_1/EcEvrProto_routed.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Performance_ExplorePostRoutePhysOpt" -objects $obj
#TS set_property -name "steps.opt_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/opt.tcl"]" -objects $obj
#TS set_property -name "steps.opt_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/opt.tcl"]" -objects $obj
set_property -name "steps.opt_design.args.directive" -value "Explore" -objects $obj
#TS set_property -name "steps.power_opt_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/power_opt.tcl"]" -objects $obj
#TS set_property -name "steps.power_opt_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/power_opt.tcl"]" -objects $obj
#TS set_property -name "steps.place_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/place.tcl"]" -objects $obj
#TS set_property -name "steps.place_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/place.tcl"]" -objects $obj
set_property -name "steps.place_design.args.directive" -value "Explore" -objects $obj
#TS set_property -name "steps.post_place_power_opt_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/post_place_power_opt.tcl"]" -objects $obj
#TS set_property -name "steps.post_place_power_opt_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/post_place_power_opt.tcl"]" -objects $obj
#TS set_property -name "steps.phys_opt_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/phys_opt.tcl"]" -objects $obj
#TS set_property -name "steps.phys_opt_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/phys_opt.tcl"]" -objects $obj
set_property -name "steps.phys_opt_design.args.directive" -value "Explore" -objects $obj
#TS set_property -name "steps.route_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/route.tcl"]" -objects $obj
#TS set_property -name "steps.route_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/route.tcl"]" -objects $obj
set_property -name "steps.route_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.route_design.args.more options" -value "-tns_cleanup" -objects $obj
set_property -name "steps.post_route_phys_opt_design.is_enabled" -value "1" -objects $obj
#TS set_property -name "steps.post_route_phys_opt_design.tcl.pre" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/pre/post_route_phys_opt.tcl"]" -objects $obj
#TS set_property -name "steps.post_route_phys_opt_design.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/post_route_phys_opt.tcl"]" -objects $obj
set_property -name "steps.post_route_phys_opt_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.write_bitstream.tcl.pre" -value "[file normalize "$origin_dir/../vivado/pre_bitstream.tcl"]" -objects $obj
#TS set_property -name "steps.write_bitstream.tcl.post" -value "[file normalize "$origin_dir/../submodules/ruckus/vivado/run/post/gui_write.tcl"]" -objects $obj
set_property -name "steps.write_bitstream.args.bin_file" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
