      - Preamble:
      - OOF2_DIV_SEL:          !<value> 0x0D
      - OOF3_DIV_SEL:          !<value> 0x0D
      - OOF2_RATIO_REF:        !<value> 0x13D5555
      - LOL_CLR_DELAY_DIV256:  !<value> 0x0000617B
      - P2_NUM:                !<value> 0x00000000003C
      - P3_NUM:                !<value> 0x00000000003C
      - MXAXB_NUM:             !<value> 0x0D040000000
      - MXAXB_DEN:             !<value> 0xC0000000
      - N0_NUM:                !<value> 0x01C00000000
      - M_NUM:                 !<value> 0x0002A000000000
      - HOLD_15M_CYC_COUNT:    !<value> 0x000349
      - Postamble:
