# Load RUCKUS environment and library
source -quiet $::env(RUCKUS_DIR)/vivado_proc.tcl

# Load common and sub-module ruckus.tcl files
loadRuckusTcl $::env(PROJ_DIR)/../../

if {[regexp {^XC7Z} "$::env(PRJ_PART)"]} {
if { [llength [get_ips processing_system7_0]] == 0 } {
    create_ip -name processing_system7 -vendor xilinx.com -library ip -module_name processing_system7_0

    # generated from Trenz reference design with vivado/gui
	set_property -dict [list \
		CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
		CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
		CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} \
		CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {125.000000} \
		CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
		CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
		CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {100.000000} \
		CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
		CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {166.666672} \
		CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
		CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} \
		CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_ARMPLL_CTRL_FBDIV {40} \
		CONFIG.PCW_CAN_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_CAN_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_CLK0_FREQ {125000000} \
		CONFIG.PCW_CLK1_FREQ {10000000} \
		CONFIG.PCW_CLK2_FREQ {10000000} \
		CONFIG.PCW_CLK3_FREQ {10000000} \
		CONFIG.PCW_CPU_CPU_PLL_FREQMHZ {1333.333} \
		CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 {2} \
		CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 {15} \
		CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 {7} \
		CONFIG.PCW_DDRPLL_CTRL_FBDIV {32} \
		CONFIG.PCW_DDR_DDR_PLL_FREQMHZ {1066.667} \
		CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 {2} \
		CONFIG.PCW_DDR_RAM_HIGHADDR {0x3FFFFFFF} \
		CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
		CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {1} \
		CONFIG.PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} \
		CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
		CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR0 {8} \
		CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
		CONFIG.PCW_ENET0_RESET_ENABLE {1} \
		CONFIG.PCW_ENET0_RESET_IO {MIO 50} \
		CONFIG.PCW_ENET1_ENET1_IO {<Select>} \
		CONFIG.PCW_ENET1_GRP_MDIO_ENABLE {0} \
		CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
		CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_ENET1_PERIPHERAL_ENABLE {0} \
		CONFIG.PCW_ENET1_PERIPHERAL_FREQMHZ {1000 Mbps} \
		CONFIG.PCW_ENET1_RESET_ENABLE {0} \
		CONFIG.PCW_ENET_RESET_ENABLE {1} \
		CONFIG.PCW_ENET_RESET_SELECT {Share reset pin} \
		CONFIG.PCW_EN_EMIO_CD_SDIO0 {0} \
		CONFIG.PCW_EN_EMIO_ENET0 {0} \
		CONFIG.PCW_EN_EMIO_ENET1 {0} \
		CONFIG.PCW_EN_EMIO_I2C0 {0} \
		CONFIG.PCW_EN_EMIO_I2C1 {0} \
		CONFIG.PCW_EN_EMIO_PJTAG {0} \
		CONFIG.PCW_EN_EMIO_SPI0 {1} \
		CONFIG.PCW_EN_EMIO_SPI1 {0} \
		CONFIG.PCW_EN_EMIO_UART0 {0} \
		CONFIG.PCW_EN_EMIO_WP_SDIO0 {0} \
		CONFIG.PCW_EN_ENET0 {1} \
		CONFIG.PCW_EN_ENET1 {0} \
		CONFIG.PCW_EN_GPIO {1} \
		CONFIG.PCW_EN_I2C0 {1} \
		CONFIG.PCW_EN_I2C1 {1} \
		CONFIG.PCW_EN_PJTAG {0} \
		CONFIG.PCW_EN_QSPI {1} \
		CONFIG.PCW_EN_RST1_PORT {1} \
		CONFIG.PCW_EN_SDIO0 {1} \
		CONFIG.PCW_EN_SPI0 {1} \
		CONFIG.PCW_SPI0_GRP_SS0_ENABLE {1} \
		CONFIG.PCW_SPI0_GRP_SS0_IO {EMIO} \
		CONFIG.PCW_SPI0_GRP_SS1_ENABLE {1} \
		CONFIG.PCW_SPI0_GRP_SS1_IO {EMIO} \
		CONFIG.PCW_SPI0_GRP_SS2_ENABLE {1} \
		CONFIG.PCW_SPI0_GRP_SS2_IO {EMIO} \
		CONFIG.PCW_SPI0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_SPI0_SPI0_IO    {EMIO} \
		CONFIG.PCW_EN_SPI1 {0} \
		CONFIG.PCW_EN_UART0 {1} \
		CONFIG.PCW_EN_USB0 {1} \
		CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0 {10} \
		CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 {2} \
		CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} \
		CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {50} \
		CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
		CONFIG.PCW_FPGA_FCLK1_ENABLE {0} \
		CONFIG.PCW_FPGA_FCLK2_ENABLE {0} \
		CONFIG.PCW_FPGA_FCLK3_ENABLE {0} \
		CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
		CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} \
		CONFIG.PCW_I2C0_GRP_INT_ENABLE {0} \
		CONFIG.PCW_I2C0_I2C0_IO {MIO 10 .. 11} \
		CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_I2C0_RESET_ENABLE {0} \
		CONFIG.PCW_I2C1_GRP_INT_ENABLE {0} \
		CONFIG.PCW_I2C1_I2C1_IO {MIO 48 .. 49} \
		CONFIG.PCW_I2C1_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_I2C1_RESET_ENABLE {0} \
		CONFIG.PCW_I2C_PERIPHERAL_FREQMHZ {111.111115} \
		CONFIG.PCW_I2C_RESET_ENABLE {0} \
		CONFIG.PCW_IOPLL_CTRL_FBDIV {30} \
		CONFIG.PCW_IO_IO_PLL_FREQMHZ {1000.000} \
		CONFIG.PCW_IRQ_F2P_INTR {1} \
		CONFIG.PCW_NUM_F2P_INTR_INPUTS {16} \
		CONFIG.PCW_MIO_0_DIRECTION {in} \
		CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_0_PULLUP {enabled} \
		CONFIG.PCW_MIO_0_SLEW {slow} \
		CONFIG.PCW_MIO_10_DIRECTION {inout} \
		CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_10_PULLUP {enabled} \
		CONFIG.PCW_MIO_10_SLEW {slow} \
		CONFIG.PCW_MIO_11_DIRECTION {inout} \
		CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_11_PULLUP {enabled} \
		CONFIG.PCW_MIO_11_SLEW {slow} \
		CONFIG.PCW_MIO_12_DIRECTION {inout} \
		CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_12_PULLUP {enabled} \
		CONFIG.PCW_MIO_12_SLEW {slow} \
		CONFIG.PCW_MIO_13_DIRECTION {inout} \
		CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_13_PULLUP {enabled} \
		CONFIG.PCW_MIO_13_SLEW {slow} \
		CONFIG.PCW_MIO_14_DIRECTION {in} \
		CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_14_PULLUP {enabled} \
		CONFIG.PCW_MIO_14_SLEW {slow} \
		CONFIG.PCW_MIO_15_DIRECTION {out} \
		CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_15_PULLUP {enabled} \
		CONFIG.PCW_MIO_15_SLEW {slow} \
		CONFIG.PCW_MIO_16_DIRECTION {out} \
		CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_16_PULLUP {enabled} \
		CONFIG.PCW_MIO_16_SLEW {slow} \
		CONFIG.PCW_MIO_17_DIRECTION {out} \
		CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_17_PULLUP {enabled} \
		CONFIG.PCW_MIO_17_SLEW {slow} \
		CONFIG.PCW_MIO_18_DIRECTION {out} \
		CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_18_PULLUP {enabled} \
		CONFIG.PCW_MIO_18_SLEW {slow} \
		CONFIG.PCW_MIO_19_DIRECTION {out} \
		CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_19_PULLUP {enabled} \
		CONFIG.PCW_MIO_19_SLEW {slow} \
		CONFIG.PCW_MIO_1_DIRECTION {out} \
		CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_1_PULLUP {enabled} \
		CONFIG.PCW_MIO_1_SLEW {slow} \
		CONFIG.PCW_MIO_20_DIRECTION {out} \
		CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_20_PULLUP {enabled} \
		CONFIG.PCW_MIO_20_SLEW {slow} \
		CONFIG.PCW_MIO_21_DIRECTION {out} \
		CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_21_PULLUP {enabled} \
		CONFIG.PCW_MIO_21_SLEW {slow} \
		CONFIG.PCW_MIO_22_DIRECTION {in} \
		CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_22_PULLUP {enabled} \
		CONFIG.PCW_MIO_22_SLEW {slow} \
		CONFIG.PCW_MIO_23_DIRECTION {in} \
		CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_23_PULLUP {enabled} \
		CONFIG.PCW_MIO_23_SLEW {slow} \
		CONFIG.PCW_MIO_24_DIRECTION {in} \
		CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_24_PULLUP {enabled} \
		CONFIG.PCW_MIO_24_SLEW {slow} \
		CONFIG.PCW_MIO_25_DIRECTION {in} \
		CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_25_PULLUP {enabled} \
		CONFIG.PCW_MIO_25_SLEW {slow} \
		CONFIG.PCW_MIO_26_DIRECTION {in} \
		CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_26_PULLUP {enabled} \
		CONFIG.PCW_MIO_26_SLEW {slow} \
		CONFIG.PCW_MIO_27_DIRECTION {in} \
		CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_27_PULLUP {enabled} \
		CONFIG.PCW_MIO_27_SLEW {slow} \
		CONFIG.PCW_MIO_28_DIRECTION {inout} \
		CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_28_PULLUP {enabled} \
		CONFIG.PCW_MIO_28_SLEW {slow} \
		CONFIG.PCW_MIO_29_DIRECTION {in} \
		CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_29_PULLUP {enabled} \
		CONFIG.PCW_MIO_29_SLEW {slow} \
		CONFIG.PCW_MIO_2_DIRECTION {inout} \
		CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_2_PULLUP {disabled} \
		CONFIG.PCW_MIO_2_SLEW {slow} \
		CONFIG.PCW_MIO_30_DIRECTION {out} \
		CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_30_PULLUP {enabled} \
		CONFIG.PCW_MIO_30_SLEW {slow} \
		CONFIG.PCW_MIO_31_DIRECTION {in} \
		CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_31_PULLUP {enabled} \
		CONFIG.PCW_MIO_31_SLEW {slow} \
		CONFIG.PCW_MIO_32_DIRECTION {inout} \
		CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_32_PULLUP {enabled} \
		CONFIG.PCW_MIO_32_SLEW {slow} \
		CONFIG.PCW_MIO_33_DIRECTION {inout} \
		CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_33_PULLUP {enabled} \
		CONFIG.PCW_MIO_33_SLEW {slow} \
		CONFIG.PCW_MIO_34_DIRECTION {inout} \
		CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_34_PULLUP {enabled} \
		CONFIG.PCW_MIO_34_SLEW {slow} \
		CONFIG.PCW_MIO_35_DIRECTION {inout} \
		CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_35_PULLUP {enabled} \
		CONFIG.PCW_MIO_35_SLEW {slow} \
		CONFIG.PCW_MIO_36_DIRECTION {in} \
		CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_36_PULLUP {enabled} \
		CONFIG.PCW_MIO_36_SLEW {slow} \
		CONFIG.PCW_MIO_37_DIRECTION {inout} \
		CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_37_PULLUP {enabled} \
		CONFIG.PCW_MIO_37_SLEW {slow} \
		CONFIG.PCW_MIO_38_DIRECTION {inout} \
		CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_38_PULLUP {enabled} \
		CONFIG.PCW_MIO_38_SLEW {slow} \
		CONFIG.PCW_MIO_39_DIRECTION {inout} \
		CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_39_PULLUP {enabled} \
		CONFIG.PCW_MIO_39_SLEW {slow} \
		CONFIG.PCW_MIO_3_DIRECTION {inout} \
		CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_3_PULLUP {disabled} \
		CONFIG.PCW_MIO_3_SLEW {slow} \
		CONFIG.PCW_MIO_40_DIRECTION {inout} \
		CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_40_PULLUP {enabled} \
		CONFIG.PCW_MIO_40_SLEW {slow} \
		CONFIG.PCW_MIO_41_DIRECTION {inout} \
		CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_41_PULLUP {enabled} \
		CONFIG.PCW_MIO_41_SLEW {slow} \
		CONFIG.PCW_MIO_42_DIRECTION {inout} \
		CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_42_PULLUP {enabled} \
		CONFIG.PCW_MIO_42_SLEW {slow} \
		CONFIG.PCW_MIO_43_DIRECTION {inout} \
		CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_43_PULLUP {enabled} \
		CONFIG.PCW_MIO_43_SLEW {slow} \
		CONFIG.PCW_MIO_44_DIRECTION {inout} \
		CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_44_PULLUP {enabled} \
		CONFIG.PCW_MIO_44_SLEW {slow} \
		CONFIG.PCW_MIO_45_DIRECTION {inout} \
		CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_45_PULLUP {enabled} \
		CONFIG.PCW_MIO_45_SLEW {slow} \
		CONFIG.PCW_MIO_46_DIRECTION {inout} \
		CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_46_PULLUP {enabled} \
		CONFIG.PCW_MIO_46_SLEW {slow} \
		CONFIG.PCW_MIO_47_DIRECTION {inout} \
		CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_47_PULLUP {enabled} \
		CONFIG.PCW_MIO_47_SLEW {slow} \
		CONFIG.PCW_MIO_48_DIRECTION {inout} \
		CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_48_PULLUP {enabled} \
		CONFIG.PCW_MIO_48_SLEW {slow} \
		CONFIG.PCW_MIO_49_DIRECTION {inout} \
		CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_49_PULLUP {enabled} \
		CONFIG.PCW_MIO_49_SLEW {slow} \
		CONFIG.PCW_MIO_4_DIRECTION {inout} \
		CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_4_PULLUP {disabled} \
		CONFIG.PCW_MIO_4_SLEW {slow} \
		CONFIG.PCW_MIO_50_DIRECTION {out} \
		CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_50_PULLUP {enabled} \
		CONFIG.PCW_MIO_50_SLEW {slow} \
		CONFIG.PCW_MIO_51_DIRECTION {out} \
		CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_51_PULLUP {enabled} \
		CONFIG.PCW_MIO_51_SLEW {slow} \
		CONFIG.PCW_MIO_52_DIRECTION {out} \
		CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_52_PULLUP {enabled} \
		CONFIG.PCW_MIO_52_SLEW {slow} \
		CONFIG.PCW_MIO_53_DIRECTION {inout} \
		CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
		CONFIG.PCW_MIO_53_PULLUP {enabled} \
		CONFIG.PCW_MIO_53_SLEW {slow} \
		CONFIG.PCW_MIO_5_DIRECTION {inout} \
		CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_5_PULLUP {disabled} \
		CONFIG.PCW_MIO_5_SLEW {slow} \
		CONFIG.PCW_MIO_6_DIRECTION {out} \
		CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_6_PULLUP {disabled} \
		CONFIG.PCW_MIO_6_SLEW {slow} \
		CONFIG.PCW_MIO_7_DIRECTION {out} \
		CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_7_PULLUP {disabled} \
		CONFIG.PCW_MIO_7_SLEW {slow} \
		CONFIG.PCW_MIO_8_DIRECTION {out} \
		CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_8_PULLUP {disabled} \
		CONFIG.PCW_MIO_8_SLEW {slow} \
		CONFIG.PCW_MIO_9_DIRECTION {in} \
		CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
		CONFIG.PCW_MIO_9_PULLUP {enabled} \
		CONFIG.PCW_MIO_9_SLEW {slow} \
		CONFIG.PCW_MIO_TREE_PERIPHERALS {SD 0#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#GPIO#GPIO#SD 0#I2C 0#I2C 0#GPIO#GPIO#UART 0#UART 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#GPIO#GPIO#I2C 1#I2C 1#ENET Reset#USB Reset#Enet 0#Enet 0} \
		CONFIG.PCW_MIO_TREE_SIGNALS {wp#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#gpio[7]#gpio[8]#cd#scl#sda#gpio[12]#gpio[13]#rx#tx#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#data[4]#dir#stp#nxt#data[0]#data[1]#data[2]#data[3]#clk#data[5]#data[6]#data[7]#clk#cmd#data[0]#data[1]#data[2]#data[3]#gpio[46]#gpio[47]#scl#sda#reset#reset#mdc#mdio} \
		CONFIG.PCW_NAND_GRP_D8_ENABLE {0} \
		CONFIG.PCW_NAND_PERIPHERAL_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_A25_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_CS0_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_CS1_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_SRAM_CS0_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_SRAM_CS1_ENABLE {0} \
		CONFIG.PCW_NOR_GRP_SRAM_INT_ENABLE {0} \
		CONFIG.PCW_NOR_PERIPHERAL_ENABLE {0} \
		CONFIG.PCW_PCAP_PERIPHERAL_DIVISOR0 {5} \
		CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
		CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
		CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} \
		CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
		CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {1} \
		CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {MIO 1 .. 6} \
		CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
		CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 {5} \
		CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200} \
		CONFIG.PCW_QSPI_QSPI_IO {MIO 1 .. 6} \
		CONFIG.PCW_SD0_GRP_CD_ENABLE {1} \
		CONFIG.PCW_SD0_GRP_CD_IO {MIO 9} \
		CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
		CONFIG.PCW_SD0_GRP_WP_ENABLE {1} \
		CONFIG.PCW_SD0_GRP_WP_IO {MIO 0} \
		CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} \
		CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 {10} \
		CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {100} \
		CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} \
		CONFIG.PCW_SINGLE_QSPI_DATA_MODE {x4} \
		CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_SPI1_GRP_SS0_ENABLE {0} \
		CONFIG.PCW_SPI1_GRP_SS1_ENABLE {0} \
		CONFIG.PCW_SPI1_GRP_SS2_ENABLE {0} \
		CONFIG.PCW_SPI1_PERIPHERAL_ENABLE {0} \
		CONFIG.PCW_SPI_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_SPI_PERIPHERAL_VALID {0} \
		CONFIG.PCW_TPIU_PERIPHERAL_DIVISOR0 {1} \
		CONFIG.PCW_UART0_GRP_FULL_ENABLE {0} \
		CONFIG.PCW_UART0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_UART0_UART0_IO {MIO 14 .. 15} \
		CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 {10} \
		CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} \
		CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
		CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
		CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT {3} \
		CONFIG.PCW_UIPARAM_DDR_BL {8} \
		CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.012} \
		CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.011} \
		CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.012} \
		CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.015} \
		CONFIG.PCW_UIPARAM_DDR_CL {7} \
		CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT {10} \
		CONFIG.PCW_UIPARAM_DDR_CWL {6} \
		CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {4096 MBits} \
		CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {16 Bits} \
		CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3 (Low Voltage)} \
		CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41J256M16 RE-125} \
		CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT {15} \
		CONFIG.PCW_UIPARAM_DDR_SPEED_BIN {DDR3_1066F} \
		CONFIG.PCW_UIPARAM_DDR_T_FAW {40.0} \
		CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN {35.0} \
		CONFIG.PCW_UIPARAM_DDR_T_RC {48.91} \
		CONFIG.PCW_UIPARAM_DDR_T_RCD {7} \
		CONFIG.PCW_UIPARAM_DDR_T_RP {7} \
		CONFIG.PCW_USB0_PERIPHERAL_ENABLE {1} \
		CONFIG.PCW_USB0_PERIPHERAL_FREQMHZ {60} \
		CONFIG.PCW_USB0_RESET_ENABLE {1} \
		CONFIG.PCW_USB0_RESET_IO {MIO 51} \
		CONFIG.PCW_USB0_USB0_IO {MIO 28 .. 39} \
		CONFIG.PCW_USB1_RESET_ENABLE {0} \
		CONFIG.PCW_USB_RESET_ENABLE {1} \
		CONFIG.PCW_USB_RESET_SELECT {Share reset pin} \
		CONFIG.PCW_USE_FABRIC_INTERRUPT {1} \
		CONFIG.PCW_USE_HIGH_OCM {1} \
		CONFIG.PCW_USE_PS_SLCR_REGISTERS {1} \
		] [get_ips processing_system7_0]
}
}

#if { [llength [get_ips ProcSysReset]] == 0 } {
#	create_ip -name proc_sys_reset -vendor xilinx.com -library ip -module_name ProcSysReset
#}

if { $::env(IMAGE_VARIANT) == "ibert"         &&
     [llength [get_ips ibert_7series_gt_0]] == 0 } {

	# Create IP; edit in gui setting
	# line-rate (1300/7*20), refclk/(1300/7), sysclk (=FCLK0), data_width (40)

	if { [ regexp "XC7Z(015|012).*" [string toupper "$::env(PRJ_PART)"] ] } {
		set ibertIpName "ibert_7series_gtp"

		# Can't change data-width to 20 or 40, only 16 allowed
		# Get placement errors (incorrect sysclk MMCM configuration)
		# when using external SYSCLK; internal (from quad) builds...
		set  ibertProps [ list \
			CONFIG.C_PROTOCOL_MAXLINERATE_1 {3.716} \
			CONFIG.C_PROTOCOL_RXREFCLK_FREQUENCY_1 {185.800} \
			CONFIG.C_PROTOCOL_QUAD0 {Custom_1_/_3.716_Gbps} \
			CONFIG.C_RXOUTCLK_FREQUENCY {232.25} \
			CONFIG.C_SYSCLK_MODE_EXTERNAL {0} \
			CONFIG.C_SYSCLK_FREQUENCY {185.800} \
			CONFIG.C_SYSCLOCK_SOURCE_INT {QUAD112_0} \
		]
	} else {
		set ibertIpName "ibert_7series_gtx"

		set  ibertProps [ list \
			CONFIG.C_PROTOCOL_MAXLINERATE_1 {3.716} \
			CONFIG.C_PROTOCOL_RXREFCLK_FREQUENCY_1 {185.800} \
			CONFIG.C_PROTOCOL_DATAWIDTH_1 {40} \
			CONFIG.C_PROTOCOL_QUAD0 {Custom_1_/_3.716_Gbps} \
			CONFIG.C_SYSCLK_FREQUENCY {50.00} \
			CONFIG.C_RXOUTCLK_FREQUENCY {92.9} \
		]
	}

	create_ip -name ${ibertIpName} -vendor xilinx.com -library ip -version 3.0 -module_name ibert_7series_gt_0

	if { [info exists ibertProps] } {
		set_property -dict ${ibertProps} [get_ips ibert_7series_gt_0]
	}
}

# Load local source Code and constraints
foreach f {
  ZynqBspPkg.vhd
  Lan9254Pkg.vhd
  TE0715Impl.vhd
  ZynqIOBuf.vhd
  ZynqOBufDS.vhd
  ZynqSpiIOBuf.vhd
  Lan9254Hbi.vhd
  Lan9254HbiImpl.vhd
  AxilLan9254HbiMaster.vhd
  AxilSpiMaster.vhd
  SynchronizerBit.vhd
} {
  loadSource    -path "$::DIR_PATH/hdl/$f"
}

if { $::env(IMAGE_VARIANT) == "tbox" || $::env(IMAGE_VARIANT) == "toggle" } {
  loadSource    -path "$::DIR_PATH/hdl/TE0715-tbox.vhd"
} else {
  loadSource    -path "$::DIR_PATH/hdl/TE0715-default.vhd"
}

loadConstraints -path "$::DIR_PATH/hdl/TE0715.xdc"
loadConstraints -path "$::DIR_PATH/hdl/clock_groups.xdc"
loadConstraints -path "$::DIR_PATH/hdl/io-pins.xdc"

# some submodule ruckus.tcl's already set the strategy
# (too late for our properties.tcl).
# Override here...
set_property STRATEGY Performance_ExplorePostRoutePhysOpt [get_runs impl_1]

set_property PROCESSING_ORDER LATE    [get_files "$::DIR_PATH/hdl/clock_groups.xdc"]
set_property USED_IN {implementation} [get_files "$::DIR_PATH/hdl/clock_groups.xdc"]
